insert into Localidad (Nombre) values('RioCeballos')
insert into Localidad (Nombre) values('Capital')
insert into Localidad (Nombre) values('RioPrimero')
insert into Localidad (Nombre) values('RioSegundo')
insert into Localidad (Nombre) values('RioTercero')
insert into Localidad (Nombre) values('RioCuarto')
insert into Localidad (Nombre) values('La Falda')
insert into Localidad (Nombre) values('Colonia Caroya')
insert into Localidad (Nombre) values('Jesus Maria')
insert into Localidad (Nombre) values('Carloz Paz')
insert into Localidad (Nombre) values('Tanti')
insert into Localidad (Nombre) values('Arroyito')

insert into TipodeDni (Nombre) values('DNI')
insert into TipodeDni (Nombre) values('libreta')
insert into TipodeDni (Nombre) values('Pasaporte')
insert into TipodeDni (Nombre) values('VISA')

insert into TipodeUsuario (Nombre) values('administrador')
insert into TipodeUsuario (Nombre) values('cliente')
insert into TipodeUsuario (Nombre) values('empleado')

insert into TipodeRol(Nombre) values ('administrador')
insert into TipodeRol (Nombre) values ('Cliente')
insert into TipodeRol (Nombre) values ('repartidor')
insert into TipodeRol (Nombre) values ('ventas')
insert into TipodeRol (Nombre) values ('encargado')
insert into TipodeRol (Nombre) values ('gerente')
insert into TipodeRol (Nombre) values ('carpintero')


insert into Clientes(DNI,Nombre,Apellido,Telefono,Calle,Numero,IdTipodeDni,IdLocalidad) values ('43410903','Gino Valentin','Romano','3543579974','Colon',2345,3,2)
insert into Clientes(DNI,Nombre,Apellido,Telefono,Calle,Numero,IdTipodeDni,IdLocalidad) values ('17768215','andres jorge','perez','2361897723','Riverera indarte',4709,2,5)
insert into Clientes(DNI,Nombre,Apellido,Telefono,Calle,Numero,IdTipodeDni,IdLocalidad) values ('34781251','gregorio de la cruz','gonzales','5615790143','Colon',2345,3,4)

insert into Categoria(Nombre) Values('Mueble de interior')
insert into Categoria(Nombre) Values('Mueble de Cocina')
insert into Categoria(Nombre) Values('Mueble de Sala')
insert into Categoria(Nombre) Values('Mueble de Dormitorio')
insert into Categoria(Nombre) Values('puerta interior')
insert into Categoria(Nombre) Values('puerta de jardin Patio ')
insert into Categoria(Nombre) Values('puerta exterior ')
insert into Categoria(Nombre) Values('ventana exterior ')

insert into TipodeAcabado(Nombre) values('melanina')
insert into TipodeAcabado(Nombre) values('barniz')
insert into TipodeAcabado(Nombre) values('clasico')
insert into TipodeAcabado(Nombre) values('sabia de pino')

insert into TipodeProducto(Nombre) values ('Mueble')
insert into TipodeProducto(Nombre) values ('Abertura')

insert into TipodeMadera(Nombre) values ('pino')
insert into TipodeMadera(Nombre) values ('quebracho')
insert into TipodeMadera(Nombre) values ('roble')
insert into TipodeMadera(Nombre) values ('abedul')